#%RAML 1.0 DataType

type: object
properties:
  id?:
    type: integer
  descricao:
    type: string
  codigoBarra:
    type: string
  valor:
    type: number
  unidade:
    type: string
  idFornecedor:
    type: integer

example:
  id: 1
  descricao: "Parafuso XPTO"
  codigoBarra: "1236912391948123712388999"
  valor: 1.99
  unidade: "UN"
  idFornecedor: 123